Use this notebook for solving Reading Homework 1 questions, and for playing with NumPy before next class. 

We recreate some of the examples from https://docs.scipy.org/doc/numpy-dev/user/quickstart.html below.

In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
x = np.float32(1.0)
x

1.0

In [7]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [8]:
z.dtype

dtype('uint8')

In [9]:
x = np.array([[ 1.+0.j, 2.+0.j], [ 0.+0.j, 0.+0.j], [ 1.+1.j, 3.+0.j]]) 

In [10]:
x

array([[ 1.+0.j,  2.+0.j],
       [ 0.+0.j,  0.+0.j],
       [ 1.+1.j,  3.+0.j]])

In [11]:
np.linspace(1., 4., 6) 

array([ 1. ,  1.6,  2.2,  2.8,  3.4,  4. ])

In [12]:
np.random.random((2,3)) 

array([[ 0.40616415,  0.52289541,  0.91552096],
       [ 0.93573548,  0.34039123,  0.41685219]])

In [13]:
np.arange(13,25).reshape(2,6)

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [14]:
y = np.arange(35).reshape(5,7) 

In [15]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [16]:
y[1:5:2,::3] 

array([[ 7, 10, 13],
       [21, 24, 27]])

In [17]:
y[1:4:2,::3] 

array([[ 7, 10, 13],
       [21, 24, 27]])

In [18]:
y[0:5:2,::3] 

array([[ 0,  3,  6],
       [14, 17, 20],
       [28, 31, 34]])

In [23]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [20]:
y.sum()

595

In [21]:
y.sum(axis=1)

array([ 70,  75,  80,  85,  90,  95, 100])

In [22]:
y.sum(axis=1)

array([ 21,  70, 119, 168, 217])

In [24]:
y.max(axis=1)

array([ 6, 13, 20, 27, 34])

In [25]:
y.average(axis=0
        )

AttributeError: 'numpy.ndarray' object has no attribute 'average'

In [26]:
y.ave(axis=0)

AttributeError: 'numpy.ndarray' object has no attribute 'ave'

In [27]:
y.avg(axis=0)

AttributeError: 'numpy.ndarray' object has no attribute 'avg'

In [28]:
y.mean(axis=0)

array([ 14.,  15.,  16.,  17.,  18.,  19.,  20.])

In [29]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])